Ex1: Função que retorna a quantidade de vogais da palavra passada
rogeriofrsouza/orion-bootcamp pull request #1
Opened 2023-10-10 19:15 UTC by rogeriofrsouza

2023-10-10 19:20 UTC, rogeriofrsouza commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 1](https://trello.com/c/gx1IxDAA/124-exerc%C3%ADcio-1)

2023-10-11 02:30 UTC, matheus-yudi-newrizon requested changes

2023-10-11 02:30 UTC, matheus-yudi-newrizon commented on ex1/ex1.ts
> +  for (let i = 0; i < str.length; i++) {
Uma sugestão, aqui você poderia agrupar o conjunto de vogais em uma lista e verificar se a letra está contida nela.

2023-10-11 02:30 UTC, matheus-yudi-newrizon commented on ex1/ex1.ts
Muito bom Rogério, fez o exercício completo :+1: e considerou as vogais acentuadas.

Alguns pontos que seria bacana observarmos:
- Por questões de boas práticas, é legal sempre colocar nomes o mais descritivo possível nas variáveis, evitando abreviações.
- Documentar os métodos com a descrição de sua responabilidade, retorno, parâmetros (https://tsdoc.org/)
- Deixar um comentário no código, fica mais fácil e rápido de compreender
- Como estamos trabalhando com o typescript, sempre que possível e necessário, adicionar os tipos no retorno do método, nas variáveis e nos parâmetros.
- Durante a selecão de elementos do DOM, é legal referenciá-los por um id definido, evitando referenciar elementos não desejados.
- A exibição dos resultados no HTML estão sendo concatenadas, seria legal substituir o resultado após informar uma nova palavra

2023-10-12 00:58 UTC, matheus-yudi-newrizon approved these changes

2023-10-12 00:58 UTC, merged