Ex2: Demonstração de funções com os paradigmas funcional e imperativo
rogeriofrsouza/orion-bootcamp pull request #2
Opened 2023-10-11 16:47 UTC by rogeriofrsouza

2023-10-11 17:28 UTC, rogeriofrsouza commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 2](https://trello.com/c/wL7nWqJm/125-exerc%C3%ADcio-2)

2023-10-11 17:29 UTC, matheus-yudi-newrizon requested changes

2023-10-11 17:29 UTC, matheus-yudi-newrizon commented on ex2/ex2.ts
> +interface Pessoa {
Boa, fazer o uso de interfaces para reaproveitar os tipos é essencial no typescript :rocket:

2023-10-11 17:29 UTC, matheus-yudi-newrizon commented on ex2/ex2.ts
> +  { "id": 1, "name": "Ada Lovelace", "bio": "Ada Lovelace, foi uma matemática e escritora inglesa reconhecida por ter escrito o primeiro algoritmo para ser processado por uma máquina" },
Só um ponto legal: quando as chaves (keys) de um objeto não possuem caracteres especiais, podemos escrevê-las sem as aspas.

2023-10-11 17:29 UTC, matheus-yudi-newrizon commented on ex2/ex2.ts
> +const getBio = (id: number, lista: Pessoa[]) => lista.find(p => p.id === id)?.bio;
Uma dica: como a busca por um item pelo id é utilizada na maioria dos os métodos, poderíamos abstrair essa lógica para uma função a parte e reutilizar nos locais necessários.

2023-10-11 17:29 UTC, matheus-yudi-newrizon commented on ex2/ex2.ts
> +const imprimeLista = (lista: Pessoa[]) => lista.forEach(p => console.log(`${p.id}. ${p.name}`));
Lembrando, sempre que possível não abreviar as variáveis,

2023-10-11 17:29 UTC, matheus-yudi-newrizon commented on ex2/ex2.ts
Muito bom Rogério, vi que você entendeu os conceitos e aplicou certinho :clap: Deixei apenas alguns pontos de observação.

2023-10-11 17:29 UTC, matheus-yudi-newrizon commented on ex2/ex2.ts
> +function getBioImp(id: number): string {
Com exceção de comentários, mensagens e erros, onde podemos manter conforme a linguagem que for mais viável ao contexto, é legal sempre unificar o idioma do nosso código. Escrevendo os métodos, variáveis, tipos, etc. todos em único idioma para facilitar o entendimento e manter a padronização.

2023-10-12 01:01 UTC, matheus-yudi-newrizon approved these changes

2023-10-12 01:02 UTC, merged